---
name: Connect to Tailscale
description: Composite action to connect to Tailscale
author: irishlab-io

inputs:
  ts-client-id:
    description: Tailscale OAuth client ID
    required: true
  ts-client-secret:
    description: Tailscale OAuth client secret
    required: true
  tags:
    description: Tailscale tags
    required: false
    default: "tag:ci"

runs:
  using: "composite"
  steps:
    - name: Connect to Tailnet
      uses: tailscale/github-action@v4.1.1
      with:
        oauth-client-id: ${{ inputs.ts-client-id }}
        oauth-secret: ${{ inputs.ts-client-secret }}
        tags: ${{ inputs.tags }}
