---
name: CI - Branches
run-name: Continuous Integration on branch ${{ github.head_ref || github.ref_name }} by ${{ github.actor }}

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - dev
      - feat/*
      - fix/*
      - rel/*
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  secret:
    name: Call Git Guardian
    uses: irishlab-io/.github/.github/workflows/reusable-gitguardian.yml@main
    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  unit-test:
    needs:
      - secret
    name: Call Python | UV & Unit Tests
    uses: irishlab-io/.github/.github/workflows/reusable-python-uv.yml@main

    with:
      pytest-enable: true
      python-version: "3.14"
      working_directory: .
