---
name: CI - Main

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Pre-Commit Checks
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run Pre-Commit (prek) Checks
        uses: j178/prek-action@91fd7d7cf70ae1dee9f4f44e7dfa5d1073fe6623 # v1.0.11

        env:
          SKIP: "pytest,pin-github-action"

  secret:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    needs:
      - pre-commit
    name: Placeholder - Secret Scanning
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run Secret Scanning
        run: echo Secret Scanning
        shell: bash

  unit-test:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    needs:
      - secret
    name: Call Python | UV & Unit Tests
    uses: irishlab-io/.github/.github/workflows/reusable-python-uv.yml@cc61910f6ccf9d0f58c5c1006f42d64986eeba82 # main

    with:
      pytest-enable: true
      python_version: "3.14"
      ruff-enable: false
      ruff_version: "0.12.10"
      uv_version: "0.9.0"
      working_directory: .


  release:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    needs:
      - unit-test

    name: Version - Release bump
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.RELEASE_PAT }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.14

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@5b0848cd060263e24602d1eba03710e056ef7711 # 0.24.0
        with:
          github_token: ${{ secrets.RELEASE_PAT }}
          branch: main
